version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gym-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: gym_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
